name: Tests
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  unit-tests-ubuntu:
    name: Unit Tests Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.13

      - name: Build
        run: go build -v ./...

      - name: Running Unit Tests
        run: go test -v ./...

  unit-tests-windows:
    name: Unit Tests Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.13

      - name: Build
        run: go build -v ./...

      - name: Running Unit Tests
        run: go test -v  ./...

  unit-tests-macos:
    name: Unit Tests Mac
    runs-on: macos-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.13

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...

      - name: Running Unit Tests
        run: go test -v  ./...
