name: Tests
on:
  pull_request:
  push:
    branches: [main]
jobs:
  unit-tests-ubuntu:
    name: Unit Tests Ubuntua
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Running Unit Tests
        run: go test -v
    
  unit-tests-windows:
    name: Unit Tests Windows
    runs-on: windows-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Running Unit Tests
        run: go test -v

  unit-tests-macos:
    name: Unit Tests Windows
    runs-on: 	macos-12

    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Running Unit Tests
        run: go test -v